@baseUrl = https://localhost:5001


################################################## Game
GET {{baseUrl}}/Game/abc
#####
GET {{baseUrl}}/Game/Colors
#####
POST {{baseUrl}}/Game
Content-type: application/json

{
   "user": "abc",
   "maxGuesses": 1
}
#####
POST {{baseUrl}}/Game/attempt/abc
Content-type: application/json

{
   "colors": "xxx"
}
#####
